### ISSUE TITLE
请问可以增加类似”感兴趣的文章“这样的功能吗？

### ISSUE THREAD

**Issue by D-clock** [giscafer/hexo-theme-cafe#22]
很多个人博客在一篇文章看完后的末尾都会有**感兴趣的文章**或者**相关文章**这种推荐。举两个栗子。

![](https://diycode.b0.upaiyun.com/photo/2017/109a07f000095251c33eb1c06db9012e.png)

![](https://diycode.b0.upaiyun.com/photo/2017/6b29af6d79565dbaff2bd921059452a2.png)

**Comment by giscafer** [comment]
这个第三方插件可以实现的，有空看一下。

**Comment by giscafer** [comment]
@D-clock 已添加，推荐文章。是代码实现的，没用第三方插件，目前是随机取文章。文章个数在配置文件可以设置，默认是4篇。
效果见：http://blog.giscafer.com/2017/06/19/ionic-md-action-sheet/

**Comment by giscafer** [comment]
每篇文章都生成一样的推荐文章了，日后修复

**Comment by D-clock** [comment]
@giscafer 好滴，感谢。

**Comment by giscafer** [comment]
@D-clock 目前遇到个问题，没有找到解决方案。动态生成随机文章是可以的。但是影响了`hexo s`命令，解决方案（临时）参考https://github.com/giscafer/hexo-theme-cafe/issues/23

**Comment by D-clock** [comment]
我在Win 10环境下merge了最新代码，用hexo g 和 hexo c命令君会报错，log如下：

```
$ hexo clean
ERROR Script load failed: themes\cafe\scripts\extend.generator.js
Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (D:\Clock_Server\blog\node_modules\hexo\lib\hexo\index.js:213:21)
    at D:\Clock_Server\blog\themes\cafe\scripts\extend.generator.js:5:14
    at D:\Clock_Server\blog\node_modules\hexo\lib\hexo\index.js:229:12
    at tryCatcher (D:\Clock_Server\blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Clock_Server\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (D:\Clock_Server\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (D:\Clock_Server\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (D:\Clock_Server\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (D:\Clock_Server\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:636:18)
    at Promise._resolveCallback (D:\Clock_Server\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:431:57)
    at Promise._settlePromiseFromHandler (D:\Clock_Server\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:522:17)
    at Promise._settlePromise (D:\Clock_Server\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (D:\Clock_Server\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (D:\Clock_Server\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (D:\Clock_Server\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:636:18)
    at D:\Clock_Server\blog\node_modules\hexo\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\Clock_Server\blog\node_modules\hexo\node_modules\hexo-fs\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
INFO  Deleted database.

```

**Comment by giscafer** [comment]
npm install moment 临时解决吧。明天我去掉依赖。没注意加了这个

**Comment by D-clock** [comment]
可以了，thx！
