### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by wangzhezhe** [giscafer/hexo-theme-cafe#3]
您好，这个主题比较简洁，很喜欢。我使用的时候遇到了如下的问题（环境是 hexo: 3.2.2 hexo-cli: 1.0.2
os: Darwin 14.5.0 darwin x64）下载的0.5.4的版本，没有修改配置文件

```
Unhandled rejection TypeError: /Users/Hessen/Documents/blogongit/hexoblog/themes/cafe/layout/layout.ejs:8
    6|       <div class="outer">
    7|         <section id="main"><%- body %></section>
 >> 8|           <%- partial('_partial/widget') %>
    9|       </div>
    10|       <%- partial('_partial/footer', null, {cache: !config.relative_link}) %>
    11|     </div>

/Users/Hessen/Documents/blogongit/hexoblog/themes/cafe/layout/_partial/widget.ejs:2
    1|  <% if (theme.sidebar && theme.sidebar !== 'bottom'){ %>
 >> 2|     <%- partial('./sidebar', 
    3|     {index:page.path=='index.html',
    4|     archive:url.includes('/archives/'),
    5|     postObj:page,

undefined is not a function
    at eval (eval at <anonymous> (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:32:17)
    at eval (eval at <anonymous> (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:36:55)
    at /Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:350)
    at eval (eval at <anonymous> (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:779)
    at /Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/Hessen/Documents/blogongit/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by giscafer** [comment]
@wangzhezhe hexo框架的环境要准备好。看异常报错是`partial`方法未定义。但`partial`方法是hexo内置的全局方法。不应该报错的。

**Comment by wangzhezhe** [comment]
可能是在mac上一些依赖没有装全，在linux上是ok的，谢谢回复。@giscafer

**Comment by giscafer** [comment]
@wangzhezhe 不客气，主题上有个人的建议欢迎提issues
